export const UNIT_TRANSLATION_KEY_MAP = {
    un: "product_form_unit_un",
    par: "product_form_unit_par",
    kit: "product_form_unit_kit",
    pacote: "product_form_unit_pacote",
    caixa: "product_form_unit_caixa",
    kg: "product_form_unit_kg",
    g: "product_form_unit_g",
    l: "product_form_unit_l",
    ml: "product_form_unit_ml",
    m: "product_form_unit_m",
    cm: "product_form_unit_cm",
    m2: "product_form_unit_m2",
    m3: "product_form_unit_m3",
    hora: "product_form_unit_hora",
    dia: "product_form_unit_dia",
    semana: "product_form_unit_semana",
    mes: "product_form_unit_mes",
    servico: "product_form_unit_servico",
    peca: "product_form_unit_peca",
  } as const;