export const LOCATION_SUGGESTIONS = [
  // Mozambique
  'Maputo',
  'Maputo, Mozambique',
  'Cidade de Maputo, Mozambique',
  'Baixa de Maputo, Mozambique',
  'Polana, Maputo, Mozambique',
  'Polana Cimento, Maputo, Mozambique',
  'Costa do Sol, Maputo, Mozambique',
  'Magoanine, Maputo, Mozambique',
  'Zimpeto',
  'Zimpeto, Maputo, Mozambique',
  'Bairro do Zimpeto, Maputo, Mozambique',
  'ISCTEM',
  'ISCTEM, Maputo, Mozambique',
  'Universidade Eduardo Mondlane',
  'Universidade Eduardo Mondlane, Maputo, Mozambique',
  'UEM, Maputo, Mozambique',
  'Matola',
  'Matola, Mozambique',
  'Matola Gare, Mozambique',
  'Machava',
  'Machava, Matola, Mozambique',
  'Boane, Mozambique',
  'Marracuene, Mozambique',
  'Xai-Xai, Mozambique',
  'Chimoio, Mozambique',
  'Beira',
  'Beira, Mozambique',
  'Tete',
  'Tete, Mozambique',
  'Nampula, Mozambique',
  'Pemba, Mozambique',
  'Quelimane, Mozambique',
  'Nacala, Mozambique',
  'Inhambane, Mozambique',

  // India
  'India',
  'Punjab, India',
  'Ludhiana',
  'Ludhiana, Punjab, India',
  'CT University',
  'CT University Ludhiana',
  'CT University, Ludhiana, Punjab, India',
  'CTU',
  'CTU Ludhiana',
  'Jalandhar, Punjab, India',
  'Amritsar, Punjab, India',
  'Chandigarh, India',
  'Delhi, India',
  'New Delhi, India',
  'Mumbai, India',
  'Bangalore, India',
  'Bengaluru, India',
  'Hyderabad, India',
  'Chennai, India',
  'Kolkata, India',
  'Pune, India',
  'Ahmedabad, India',
  'Jaipur, India',
  'Goa, India',
  'Kochi, India',

  // South Africa
  'South Africa',
  'Johannesburg, South Africa',
  'Sandton, Johannesburg, South Africa',
  'Pretoria, South Africa',
  'Cape Town, South Africa',
  'Durban, South Africa',
  'Soweto, South Africa',
  'Port Elizabeth, South Africa',

  // Africa
  'Nairobi, Kenya',
  'Mombasa, Kenya',
  'Kigali, Rwanda',
  'Dar es Salaam, Tanzania',
  'Lagos, Nigeria',
  'Abuja, Nigeria',
  'Accra, Ghana',
  'Cairo, Egypt',
  'Casablanca, Morocco',
  'Addis Ababa, Ethiopia',
  'Luanda, Angola',
  'Harare, Zimbabwe',

  // Europe
  'London, United Kingdom',
  'Manchester, United Kingdom',
  'Birmingham, United Kingdom',
  'Paris, France',
  'Marseille, France',
  'Berlin, Germany',
  'Munich, Germany',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Lisbon, Portugal',
  'Porto, Portugal',
  'Rome, Italy',
  'Milan, Italy',
  'Amsterdam, Netherlands',
  'Brussels, Belgium',
  'Dublin, Ireland',
  'Zurich, Switzerland',
  'Vienna, Austria',
  'Prague, Czech Republic',
  'Warsaw, Poland',

  // Middle East
  'Dubai, United Arab Emirates',
  'Abu Dhabi, United Arab Emirates',
  'Doha, Qatar',
  'Riyadh, Saudi Arabia',
  'Jeddah, Saudi Arabia',
  'Istanbul, Türkiye',

  // Asia
  'Singapore',
  'Kuala Lumpur, Malaysia',
  'Bangkok, Thailand',
  'Jakarta, Indonesia',
  'Manila, Philippines',
  'Hong Kong',
  'Tokyo, Japan',
  'Osaka, Japan',
  'Seoul, South Korea',
  'Beijing, China',
  'Shanghai, China',

  // North America
  'New York, United States',
  'Manhattan, New York, United States',
  'Brooklyn, New York, United States',
  'Los Angeles, United States',
  'San Francisco, United States',
  'Chicago, United States',
  'Houston, United States',
  'Miami, United States',
  'Toronto, Canada',
  'Vancouver, Canada',
  'Montreal, Canada',

  // South America
  'São Paulo, Brazil',
  'Rio de Janeiro, Brazil',
  'Brasília, Brazil',
  'Buenos Aires, Argentina',
  'Santiago, Chile',
  'Lima, Peru',
  'Bogotá, Colombia',

  // Oceania
  'Sydney, Australia',
  'Melbourne, Australia',
  'Brisbane, Australia',
  'Auckland, New Zealand',

  // Generic helpers
  'University',
  'College',
  'Campus',
  'School',
  'Hospital',
  'Airport',
  'Bus Terminal',
  'Train Station',
  'Main Road',
  'City Center',
  'Downtown',
  'Mall',
  'Market',
  'Beach',
  'Harbor',
  'Port',
];