export const LOCATION_SUGGESTIONS = [
  // Mozambique
  'Mozambique',
  'Maputo',
  'Maputo, Mozambique',
  'Cidade de Maputo, Mozambique',
  'Baixa de Maputo, Mozambique',
  'Polana, Maputo, Mozambique',
  'Polana Cimento, Maputo, Mozambique',
  'Polana Cimento A, Maputo, Mozambique',
  'Polana Cimento B, Maputo, Mozambique',
  'Sommerschield, Maputo, Mozambique',
  'Sommerschield I, Maputo, Mozambique',
  'Sommerschield II, Maputo, Mozambique',
  'Coop, Maputo, Mozambique',
  'Central C, Maputo, Mozambique',
  'Malhangalene, Maputo, Mozambique',
  'Malhangalene A, Maputo, Mozambique',
  'Malhangalene B, Maputo, Mozambique',
  'Alto Maé, Maputo, Mozambique',
  'Alto Maé A, Maputo, Mozambique',
  'Alto Maé B, Maputo, Mozambique',
  'Alto Maé C, Maputo, Mozambique',
  'Julius Nyerere, Maputo, Mozambique',
  'Triunfo, Maputo, Mozambique',
  'Costa do Sol, Maputo, Mozambique',
  'Bairro dos Pescadores, Maputo, Mozambique',
  'Magoanine, Maputo, Mozambique',
  'Magoanine A, Maputo, Mozambique',
  'Magoanine B, Maputo, Mozambique',
  'Magoanine C, Maputo, Mozambique',
  'Magoanine, Maputo, Mozambique',
  'Laulane, Maputo, Mozambique',
  'Laulane A, Maputo, Mozambique',
  'Laulane B, Maputo, Mozambique',
  'Hulene, Maputo, Mozambique',
  'Hulene A, Maputo, Mozambique',
  'Hulene B, Maputo, Mozambique',
  'Hulene, Maputo, Mozambique',
  'Maxaquene, Maputo, Mozambique',
  'Maxaquene A, Maputo, Mozambique',
  'Maxaquene B, Maputo, Mozambique',
  'Maxaquene C, Maputo, Mozambique',
  'Maxaquene D, Maputo, Mozambique',
  'Mafalala, Maputo, Mozambique',
  'Chamanculo, Maputo, Mozambique',
  'Chamanculo A, Maputo, Mozambique',
  'Chamanculo B, Maputo, Mozambique',
  'Chamanculo C, Maputo, Mozambique',
  'Xipamanine, Maputo, Mozambique',
  'Minkadjuíne, Maputo, Mozambique',
  'Munhuana, Maputo, Mozambique',
  'Aeroporto A, Maputo, Mozambique',
  'Aeroporto B, Maputo, Mozambique',
  'Unidade 7, Maputo, Mozambique',
  '3 de Fevereiro, Maputo, Mozambique',
  'Ferroviário, Maputo, Mozambique',
  'Benfica, Maputo, Mozambique',
  'Zimpeto',
  'Zimpeto, Maputo, Mozambique',
  'Bairro do Zimpeto, Maputo, Mozambique',
  'Albazine, Maputo, Mozambique',
  'Inhagoia, Maputo, Mozambique',
  'Inhagoia A, Maputo, Mozambique',
  'Inhagoia B, Maputo, Mozambique',
  'George Dimitrov, Maputo, Mozambique',
  'Bagamoyo, Maputo, Mozambique',
  'FPLM, Maputo, Mozambique',
  'Tsalala, Maputo, Mozambique',
  'Mahotas, Maputo, Mozambique',
  'Marracuene, Maputo Province, Mozambique',
  'Michafutene, Maputo Province, Mozambique',
  'Katembe, Maputo, Mozambique',
  'Inhaca, Maputo, Mozambique',
  'Ponta do Ouro, Maputo Province, Mozambique',
  'Namaacha, Maputo Province, Mozambique',
  'Boane, Mozambique',
  'Boane Sede, Mozambique',
  'Belo Horizonte, Boane, Mozambique',
  'Matola',
  'Matola, Mozambique',
  'Cidade da Matola, Mozambique',
  'Matola Gare, Mozambique',
  'Machava',
  'Machava, Matola, Mozambique',
  'Machava Sede, Matola, Mozambique',
  'Patrice Lumumba, Matola, Mozambique',
  'Liberdade, Matola, Mozambique',
  'Matola Rio, Mozambique',
  'Matola A, Mozambique',
  'Matola B, Mozambique',
  'Muhalaze, Matola, Mozambique',
  'Nkobe, Matola, Mozambique',
  'Khongolote, Matola, Mozambique',
  'Tchumene, Matola, Mozambique',
  'Tchumene I, Matola, Mozambique',
  'Tchumene II, Matola, Mozambique',
  'Malhampsene, Matola, Mozambique',
  'Mali, Matola, Mozambique',
  'Bunhiça, Matola, Mozambique',
  'Fomento, Matola, Mozambique',
  'Infulene, Matola, Mozambique',
  'Intaka, Matola, Mozambique',
  'Sikwama, Matola, Mozambique',
  'Trevo da Matola, Mozambique',
  'Condomínio Matola, Mozambique',
  'Xinavane, Maputo Province, Mozambique',
  'Manhiça, Maputo Province, Mozambique',
  'Moamba, Maputo Province, Mozambique',
  'Bilene, Gaza, Mozambique',
  'Xai-Xai, Mozambique',
  'Chókwè, Gaza, Mozambique',
  'Chibuto, Gaza, Mozambique',
  'Maxixe, Inhambane, Mozambique',
  'Inhambane, Mozambique',
  'Tofo, Inhambane, Mozambique',
  'Vilankulo, Mozambique',
  'Massinga, Inhambane, Mozambique',
  'Beira',
  'Beira, Mozambique',
  'Cidade da Beira, Mozambique',
  'Macúti, Beira, Mozambique',
  'Ponta-Gêa, Beira, Mozambique',
  'Munhava, Beira, Mozambique',
  'Esturro, Beira, Mozambique',
  'Chaimite, Beira, Mozambique',
  'Manga, Beira, Mozambique',
  'Palmeiras, Beira, Mozambique',
  'Dondo, Sofala, Mozambique',
  'Chimoio, Mozambique',
  'Bairro 1, Chimoio, Mozambique',
  'Bairro 2, Chimoio, Mozambique',
  'Bairro 3, Chimoio, Mozambique',
  'Bairro 4, Chimoio, Mozambique',
  'Manica, Mozambique',
  'Tete',
  'Tete, Mozambique',
  'Cidade de Tete, Mozambique',
  'Matundo, Tete, Mozambique',
  'Chingodzi, Tete, Mozambique',
  'Moatize, Tete, Mozambique',
  'Nampula, Mozambique',
  'Cidade de Nampula, Mozambique',
  'Natikiri, Nampula, Mozambique',
  'Namicopo, Nampula, Mozambique',
  'Nacala, Mozambique',
  'Nacala Porto, Mozambique',
  'Pemba, Mozambique',
  'Cidade de Pemba, Mozambique',
  'Quelimane, Mozambique',
  'Ilha de Moçambique, Nampula, Mozambique',
  'Lichinga, Niassa, Mozambique',
  'Cuamba, Niassa, Mozambique',
  'Montepuez, Cabo Delgado, Mozambique',

  // Universities and institutions in Mozambique
  'ISCTEM',
  'ISCTEM, Maputo, Mozambique',
  'Universidade Eduardo Mondlane',
  'Universidade Eduardo Mondlane, Maputo, Mozambique',
  'UEM, Maputo, Mozambique',
  'Universidade Pedagógica, Maputo, Mozambique',
  'Universidade Politécnica, Maputo, Mozambique',
  'Universidade Católica de Moçambique, Beira, Mozambique',
  'Instituto Superior de Transportes e Comunicações, Maputo, Mozambique',

  // India
  'India',
  'Punjab, India',
  'Ludhiana',
  'Ludhiana, Punjab, India',
  'Model Town, Ludhiana, Punjab, India',
  'Civil Lines, Ludhiana, Punjab, India',
  'Dugri, Ludhiana, Punjab, India',
  'Sarabha Nagar, Ludhiana, Punjab, India',
  'Pakhowal Road, Ludhiana, Punjab, India',
  'Ferozepur Road, Ludhiana, Punjab, India',
  'Gill Road, Ludhiana, Punjab, India',
  'Haibowal, Ludhiana, Punjab, India',
  'Shimlapuri, Ludhiana, Punjab, India',
  'BRS Nagar, Ludhiana, Punjab, India',
  'Rajguru Nagar, Ludhiana, Punjab, India',
  'Moti Nagar, Ludhiana, Punjab, India',
  'Samrala Chowk, Ludhiana, Punjab, India',
  'Khanna, Punjab, India',
  'Doraha, Punjab, India',
  'Phagwara, Punjab, India',
  'Jalandhar, Punjab, India',
  'Model Town, Jalandhar, Punjab, India',
  'Urban Estate, Jalandhar, Punjab, India',
  'Amritsar, Punjab, India',
  'Ranjit Avenue, Amritsar, Punjab, India',
  'Patiala, Punjab, India',
  'Mohali, Punjab, India',
  'Zirakpur, Punjab, India',
  'Bathinda, Punjab, India',
  'Chandigarh, India',
  'Sector 17, Chandigarh, India',
  'Sector 22, Chandigarh, India',
  'Sector 35, Chandigarh, India',
  'Delhi, India',
  'New Delhi, India',
  'Connaught Place, New Delhi, India',
  'Karol Bagh, New Delhi, India',
  'Saket, New Delhi, India',
  'Rohini, Delhi, India',
  'Dwarka, New Delhi, India',
  'Mumbai, India',
  'Andheri, Mumbai, India',
  'Bandra, Mumbai, India',
  'Powai, Mumbai, India',
  'Navi Mumbai, India',
  'Bangalore, India',
  'Bengaluru, India',
  'Whitefield, Bengaluru, India',
  'Koramangala, Bengaluru, India',
  'Indiranagar, Bengaluru, India',
  'HSR Layout, Bengaluru, India',
  'Electronic City, Bengaluru, India',
  'Hyderabad, India',
  'Banjara Hills, Hyderabad, India',
  'Hitech City, Hyderabad, India',
  'Gachibowli, Hyderabad, India',
  'Chennai, India',
  'T Nagar, Chennai, India',
  'Velachery, Chennai, India',
  'Adyar, Chennai, India',
  'Kolkata, India',
  'Salt Lake, Kolkata, India',
  'Park Street, Kolkata, India',
  'Pune, India',
  'Hinjewadi, Pune, India',
  'Kothrud, Pune, India',
  'Viman Nagar, Pune, India',
  'Ahmedabad, India',
  'Jaipur, India',
  'Goa, India',
  'Panaji, Goa, India',
  'Margao, Goa, India',
  'Kochi, India',
  'Ernakulam, Kochi, India',

  // Universities and institutions in India
  'CT University',
  'CT University Ludhiana',
  'CT University, Ludhiana, Punjab, India',
  'CTU',
  'CTU Ludhiana',
  'Lovely Professional University, Punjab, India',
  'Punjab University, Chandigarh, India',
  'Delhi University, New Delhi, India',
  'IIT Delhi, New Delhi, India',
  'IIT Bombay, Mumbai, India',
  'IIT Madras, Chennai, India',
  'IIT Kanpur, Uttar Pradesh, India',

  // South Africa
  'South Africa',
  'Johannesburg, South Africa',
  'Sandton, Johannesburg, South Africa',
  'Rosebank, Johannesburg, South Africa',
  'Midrand, Johannesburg, South Africa',
  'Soweto, Johannesburg, South Africa',
  'Pretoria, South Africa',
  'Centurion, Pretoria, South Africa',
  'Arcadia, Pretoria, South Africa',
  'Hatfield, Pretoria, South Africa',
  'Cape Town, South Africa',
  'Sea Point, Cape Town, South Africa',
  'Green Point, Cape Town, South Africa',
  'Woodstock, Cape Town, South Africa',
  'Claremont, Cape Town, South Africa',
  'Bellville, Cape Town, South Africa',
  'Durban, South Africa',
  'Umhlanga, Durban, South Africa',
  'Berea, Durban, South Africa',
  'Port Elizabeth, South Africa',
  'Gqeberha, South Africa',
  'Bloemfontein, South Africa',
  'Polokwane, South Africa',
  'Nelspruit, South Africa',
  'Mbombela, South Africa',
  'East London, South Africa',
  'Kimberley, South Africa',

  // Africa
  'Nairobi, Kenya',
  'Westlands, Nairobi, Kenya',
  'Karen, Nairobi, Kenya',
  'Kilimani, Nairobi, Kenya',
  'Mombasa, Kenya',
  'Kigali, Rwanda',
  'Nyarutarama, Kigali, Rwanda',
  'Dar es Salaam, Tanzania',
  'Masaki, Dar es Salaam, Tanzania',
  'Mikocheni, Dar es Salaam, Tanzania',
  'Lagos, Nigeria',
  'Victoria Island, Lagos, Nigeria',
  'Lekki, Lagos, Nigeria',
  'Ikeja, Lagos, Nigeria',
  'Abuja, Nigeria',
  'Wuse, Abuja, Nigeria',
  'Maitama, Abuja, Nigeria',
  'Accra, Ghana',
  'East Legon, Accra, Ghana',
  'Cairo, Egypt',
  'Casablanca, Morocco',
  'Addis Ababa, Ethiopia',
  'Bole, Addis Ababa, Ethiopia',
  'Luanda, Angola',
  'Talatona, Luanda, Angola',
  'Harare, Zimbabwe',
  'Borrowdale, Harare, Zimbabwe',

  // Europe
  'London, United Kingdom',
  'Central London, United Kingdom',
  'Canary Wharf, London, United Kingdom',
  'Westminster, London, United Kingdom',
  'Croydon, London, United Kingdom',
  'Manchester, United Kingdom',
  'Salford, Manchester, United Kingdom',
  'Birmingham, United Kingdom',
  'Paris, France',
  'La Défense, Paris, France',
  'Montmartre, Paris, France',
  'Marseille, France',
  'Berlin, Germany',
  'Mitte, Berlin, Germany',
  'Charlottenburg, Berlin, Germany',
  'Munich, Germany',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Eixample, Barcelona, Spain',
  'Lisbon, Portugal',
  'Alfama, Lisbon, Portugal',
  'Parque das Nações, Lisbon, Portugal',
  'Porto, Portugal',
  'Rome, Italy',
  'Milan, Italy',
  'Navigli, Milan, Italy',
  'Amsterdam, Netherlands',
  'Brussels, Belgium',
  'Dublin, Ireland',
  'Zurich, Switzerland',
  'Vienna, Austria',
  'Prague, Czech Republic',
  'Warsaw, Poland',

  // Middle East
  'Dubai, United Arab Emirates',
  'Downtown Dubai, United Arab Emirates',
  'Dubai Marina, United Arab Emirates',
  'Business Bay, Dubai, United Arab Emirates',
  'Jumeirah, Dubai, United Arab Emirates',
  'Abu Dhabi, United Arab Emirates',
  'Doha, Qatar',
  'West Bay, Doha, Qatar',
  'Riyadh, Saudi Arabia',
  'Jeddah, Saudi Arabia',
  'Istanbul, Türkiye',
  'Taksim, Istanbul, Türkiye',
  'Kadıköy, Istanbul, Türkiye',

  // Asia
  'Singapore',
  'Orchard, Singapore',
  'Marina Bay, Singapore',
  'Jurong, Singapore',
  'Kuala Lumpur, Malaysia',
  'Bukit Bintang, Kuala Lumpur, Malaysia',
  'Bangsar, Kuala Lumpur, Malaysia',
  'Bangkok, Thailand',
  'Sukhumvit, Bangkok, Thailand',
  'Jakarta, Indonesia',
  'Central Jakarta, Indonesia',
  'Manila, Philippines',
  'Makati, Manila, Philippines',
  'Hong Kong',
  'Central, Hong Kong',
  'Kowloon, Hong Kong',
  'Tokyo, Japan',
  'Shibuya, Tokyo, Japan',
  'Shinjuku, Tokyo, Japan',
  'Osaka, Japan',
  'Namba, Osaka, Japan',
  'Seoul, South Korea',
  'Gangnam, Seoul, South Korea',
  'Hongdae, Seoul, South Korea',
  'Beijing, China',
  'Shanghai, China',
  'Pudong, Shanghai, China',

  // North America
  'New York, United States',
  'Manhattan, New York, United States',
  'Brooklyn, New York, United States',
  'Queens, New York, United States',
  'Bronx, New York, United States',
  'Los Angeles, United States',
  'Hollywood, Los Angeles, United States',
  'Santa Monica, Los Angeles, United States',
  'San Francisco, United States',
  'SoMa, San Francisco, United States',
  'Silicon Valley, California, United States',
  'Chicago, United States',
  'Downtown Chicago, United States',
  'Houston, United States',
  'Miami, United States',
  'Brickell, Miami, United States',
  'Toronto, Canada',
  'Downtown Toronto, Canada',
  'North York, Toronto, Canada',
  'Vancouver, Canada',
  'Montreal, Canada',

  // South America
  'São Paulo, Brazil',
  'Avenida Paulista, São Paulo, Brazil',
  'Pinheiros, São Paulo, Brazil',
  'Vila Madalena, São Paulo, Brazil',
  'Rio de Janeiro, Brazil',
  'Copacabana, Rio de Janeiro, Brazil',
  'Ipanema, Rio de Janeiro, Brazil',
  'Barra da Tijuca, Rio de Janeiro, Brazil',
  'Brasília, Brazil',
  'Buenos Aires, Argentina',
  'Palermo, Buenos Aires, Argentina',
  'Santiago, Chile',
  'Las Condes, Santiago, Chile',
  'Lima, Peru',
  'Miraflores, Lima, Peru',
  'Bogotá, Colombia',
  'Chapinero, Bogotá, Colombia',

  // Oceania
  'Sydney, Australia',
  'Sydney CBD, Australia',
  'Parramatta, Sydney, Australia',
  'Melbourne, Australia',
  'Melbourne CBD, Australia',
  'Brisbane, Australia',
  'Auckland, New Zealand',
  'Central Auckland, New Zealand',

  // Generic helpers
  'University',
  'College',
  'Campus',
  'School',
  'Hospital',
  'Clinic',
  'Airport',
  'International Airport',
  'Bus Terminal',
  'Train Station',
  'Main Road',
  'Avenue',
  'Street',
  'Neighborhood',
  'District',
  'City Center',
  'Downtown',
  'Mall',
  'Shopping Center',
  'Market',
  'Beach',
  'Harbor',
  'Port',
  'Office Park',
  'Business Center',
  'Industrial Area',
  'Residential Area',
]